package auth.database;

import java.sql.*;

public class DatabaseConnection {
    private static Connection connection = null;

    public static Connection getConnection() {
        if (connection != null) {
            try {
                if (!connection.isClosed()) {
                    return connection;
                }
            } catch (SQLException e) {
                System.err.println("DB error: " + e.getMessage());
            }
        }

        try {
            String dbUrl = "jdbc:h2:./portfolio_db;DB_CLOSE_DELAY=-1";
            String dbUser = "sa";
            String dbPassword = "";

            Class.forName("org.h2.Driver");
            connection = DriverManager.getConnection(dbUrl, dbUser, dbPassword);
            createTables();

            System.out.println("✅ H2 Database connected!");
            System.out.println("📁 Database file: portfolio_db.mv.db");

        } catch (ClassNotFoundException e) {
            System.err.println("❌ H2 JDBC driver not found!");
        } catch (SQLException e) {
            System.err.println("❌ Database connection error: " + e.getMessage());
        }
        return connection;
    }

    private static void createTables() throws SQLException {
        // Исправленный синтаксис для H2 (без AUTO_INCREMENT)
        String createUsersTable = """
            CREATE TABLE IF NOT EXISTS users (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) UNIQUE NOT NULL,
                email VARCHAR(100) UNIQUE NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_login TIMESTAMP
            )
        """;

        String createSessionsTable = """
            CREATE TABLE IF NOT EXISTS sessions (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id VARCHAR(255) UNIQUE NOT NULL,
                user_id INT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMP NOT NULL,
                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )
        """;

        try (Statement stmt = connection.createStatement()) {
            stmt.execute(createUsersTable);
            stmt.execute(createSessionsTable);
            System.out.println("✅ Tables users and sessions created/verified");
        } catch (SQLException e) {
            System.err.println("⚠️ Table creation error: " + e.getMessage());
        }
    }

    public static void closeConnection() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                System.out.println("🔌 Database connection closed");
            }
        } catch (SQLException e) {
            System.err.println("Close connection error: " + e.getMessage());
        }
    }
}